### ISSUE TITLE
World hopping function

### ISSUE THREAD

**Issue by Tosccony** [PTYB/SlayerIssueTracker#109] opened 2023-10-18 23:53 UTC
Current behavior:  Goes to location to complete task and will take other players spot even if another players cannon is placed down.

Expected behavior: If a player is attacking npcs / cannon is placed down, hop to a world without another player in that spot.

Screenshots/Video: N/A

Additional information: I think it would be a nice feature to have the ability to world hop if another player is already fighting in the same location to not steal their spot, I've had my guy try to overtake other players spots which led to upsetting others and getting reports.

**Comment by PTYB** [comment] 2023-10-19 03:20
It is planned although it gets more complicated when areas have multiple slots. I was planning on adding sub spots per area but that is a far away from being created right now.

**Comment by Tosccony** [comment] 2023-10-19 03:51
I figured that aswell, honestly not sure how you could handle it as players could just be walking by and possibly proc the hop even though it's not needed. Adding more areas would be a good idea but once again it becomes challenging with having to add more sub spots within the same area. I understand it's a ton of extra work and as is to be honest the script is flawless, as long as you babysit a bit and catch when there's someone there already just manual hopping isn't the end of the world!

**Comment by PTYB** [comment] 2023-11-15 07:46
Duplicate of original ticket https://github.com/PTYB/SlayerIssueTracker/issues/13

**Closed by PTYB** 2023-11-15 07:46 UTC
Labels: enhancement, script
