### ISSUE TITLE
Herb sack

### ISSUE THREAD

**Issue by Robsukka** [PTYB/SlayerIssueTracker#212] opened 2024-01-20 15:05 UTC
Issue: won't put herbs in sack
Current behavior: Takes herb sack to task but won't deposit herbs to it. Theres only option to add closed herb sack in settings.
Expected behavior: use the fill option in herb sack or add "open" herb sack which collects herbs automaticly to sack. Also if could empty sack when banking.
Screenshots/Video:
Master: Konar
Task: All
Logs:
Additional information: "open" herb sack id: 24478

**Comment by PTYB** [comment] 2024-01-21 04:02
Will be part of next release

**Comment by Rallik-Pog** [comment] 2024-01-21 05:48
This has never been an issure for me, I have opened herb sack in all my setups. Not sure what the issue is.

**Comment by Robsukka** [comment] 2024-01-21 08:14
![IMG_20240121_094513](https://github.com/PTYB/SlayerIssueTracker/assets/127040593/b2a16d6d-5279-4ead-a5b4-fc76bad96e0d)
![IMG_20240121_100821](https://github.com/PTYB/SlayerIssueTracker/assets/127040593/652234b3-c5eb-4b61-9225-05e057317131)
![IMG_20240121_100737](https://github.com/PTYB/SlayerIssueTracker/assets/127040593/f6654e45-4823-414a-8761-cc2214388c40)

So the issue is that there is no option for open sack and with the closed sack wont fill it with herbs and just runs to bank when inventory is full. that id is for closed sack, dunno how can you have it on your setup. @Rallik-Pog

**Comment by PTYB** [comment] 2024-01-23 08:32
Now released

**Comment by ryant704** [comment] 2024-01-23 20:15
> Now released

Hello, you added the placeholder ID and not the open sack ID (24478).

**Comment by Rallik-Pog** [comment] 2024-01-24 02:50
> So the issue is that there is no option for open sack and with the closed sack wont fill it with herbs and just runs to bank when inventory is full. that id is for closed sack, dunno how can you have it on your setup. @Rallik-Pog

![image](https://github.com/PTYB/SlayerIssueTracker/assets/118016227/3119dbdf-b694-4df5-a937-90107e29d07c)

You have to spell it like the items name. https://oldschool.runescape.wiki/w/Herb_sack#Open
![image](https://github.com/PTYB/SlayerIssueTracker/assets/118016227/2ffc14e7-e9c4-4801-b395-0a1c4bca53dd)

![image](https://github.com/PTYB/SlayerIssueTracker/assets/118016227/6b8c20d1-0f59-4c6d-9339-8c2fc1bd8ea3)

**Comment by Robsukka** [comment] 2024-01-24 07:17
Oh i didnt know you have to write the whole name lol, thank you and sorry. 🤦

**Closed as completed** 2024-01-24 08:49 UTC
Labels: website, Awaiting test
