### ISSUE TITLE
Possibly add Herb Sack

### ISSUE THREAD

**Issue by TrippyBbPie** [PTYB/SlayerIssueTracker#112] opened 2023-10-22 04:19 UTC
Tons of herbs drop from slayer assignments and having the herb sack will help save on tons of space and banking. Also possibly implementing Emptying the Herb sack before or after each assignment so prevent any issues.

**Comment by PTYB** [comment] 2023-11-11 20:19
Added

**Comment by PTYB** [comment] 2023-11-11 20:21
Closing because duplicate of another ticket https://github.com/PTYB/SlayerIssueTracker/issues/112

**Closed by PTYB** 2023-11-11 20:21 UTC
Labels: enhancement, script, Awaiting test
