### ISSUE TITLE
Vampyre Task

### ISSUE THREAD

**Issue by TrippyBbPie** [PTYB/SlayerIssueTracker#139] opened 2023-11-14 00:28 UTC
Issue: Gets stuck behind trees that attack you and wont move
Current behavior: Sits and gets attacked and wont move
Expected behavior: click at least 1 tile away from the tree to move that way it can attack vampyres again
Screenshots/Video: 
![image](https://github.com/PTYB/SlayerIssueTracker/assets/148507398/664525bc-a29d-4250-bafc-8739832cabb2)
Master: Nieve
Task: Vampyres
Additional information:

**Comment by TrippyBbPie** [comment] 2023-11-14 00:31
[slayer.txt](https://github.com/PTYB/SlayerIssueTracker/files/13343206/slayer.txt)
Heres is logs when it happens

**Comment by PTYB** [comment] 2023-11-14 05:55
Not easy to fix , wonder if theres a better place to kill vampyres

**Comment by PTYB** [comment] 2023-11-15 07:43
Duplicate of https://github.com/PTYB/SlayerIssueTracker/issues/103

**Closed by PTYB** 2023-11-15 07:43 UTC
Labels: bug, script
