### ISSUE TITLE
Lizardman Shamans - Doesnt swap to weapon after pathing to task

### ISSUE THREAD

**Issue by iamharmor** [PTYB/SlayerIssueTracker#206] opened 2024-01-07 06:28 UTC
**Issue:** Had a dramen staff(fairy ring) as my pathing to lizardman shamans, it ran to the shamans and wouldn't swap from dramen staff to dragon hunter crossbow until i swapped it myself, then the script responded fine.
**Current behavior:** gets confused after fairy ringing and doesnt swap to weapon during task fight
**Expected behavior:** Swaps to weapon after leaving fairy ring
**Screenshots/Video:** https://gyazo.com/43b36f63dde3c17b568adf44cc2f4e7d
**Master:** Nieve
**Task:** Lizardman shaman
**Logs:** 
[liz.txt](https://github.com/PTYB/SlayerIssueTracker/files/13852482/liz.txt)
**Additional information:** yuh

**Comment by PTYB** [comment] 2024-01-10 09:34
Fix will be released tomorrow after some testing.

**Comment by PTYB** [comment] 2024-01-10 09:34
Duplicate of https://github.com/PTYB/SlayerIssueTracker/issues/188

**Closed as completed by PTYB** 2024-01-10 09:34 UTC
